name: release

on:
  schedule:
    - cron: 0 0 1 * *
  push:
    branches:
      - prime

jobs:
  release-default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Get Meta
        id: meta
        run: |
          echo IMAGE_CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ') | tee -a $GITHUB_OUTPUT
          echo IMAGE_VERSION=$(date -u +'v%y.%m.%d') | tee -a $GITHUB_OUTPUT
          echo IMAGE_REVISION=$(git rev-parse HEAD) | tee -a $GITHUB_OUTPUT

      - name: Build and push default 24.04
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfiles/ubuntu.dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          pull: true
          push: true
          no-cache: true
          build-args: |
            BASE_IMAGE_TAG=act-24.04
            IMAGE_VERSION=${{ steps.meta.outputs.IMAGE_VERSION }}
            IMAGE_CREATED=${{ steps.meta.outputs.IMAGE_CREATED }}
            IMAGE_REVISION=${{ steps.meta.outputs.IMAGE_REVISION }}
          tags: |
            Foat/runner-images:ubuntu-24.04
            Foat/runner-images:ubuntu-24.04-${{ steps.meta.outputs.IMAGE_VERSION }}
            Foat/runner-images:ubuntu-latest

      - name: Build and push default 22.04
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfiles/ubuntu.dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          pull: true
          push: true
          no-cache: true
          build-args: |
            BASE_IMAGE_TAG=act-22.04
            IMAGE_VERSION=${{ steps.meta.outputs.IMAGE_VERSION }}
            IMAGE_CREATED=${{ steps.meta.outputs.IMAGE_CREATED }}
            IMAGE_REVISION=${{ steps.meta.outputs.IMAGE_REVISION }}
          tags: |
            Foat/runner-images:ubuntu-22.04
            Foat/runner-images:ubuntu-22.04-${{ steps.meta.outputs.IMAGE_VERSION }}